language: 
  - cpp
dist: xenial
sudo: required
python: 3.7
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-7
            - ninja-build 
            - libvulkan-dev 
            - libvulkan1 
            - vulkan-utils 
            - xorg-dev 
            - libglu1-mesa-dev
            - python3.7
            - python3-pip
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && PY=python3.7 && PIP=pip3"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - python3.7 --version
  - pip3 --version
  - pip3 install --upgrade pip
  - pip3 --version
  - pip3 install setuptools --user --upgrade
  - pip3 install conan --user --upgrade
  - pip3 install pathlib --user --upgrade
  - conan user
  - conan remote add jeffw https://api.bintray.com/conan/jeffw387/conan-public
script:
  - ./run-build.sh