language: 
  - cpp
dist: xenial
sudo: required
python: 3.7
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - ninja-build 
            - libvulkan-dev 
            - libvulkan1 
            - vulkan-utils 
            - xorg-dev 
            - libglu1-mesa-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - pyenv --help
  - pyenv install 3.7.0a1
  - pyenv local 3.7.0a1
  - pip3 install setuptools --user --upgrade
  - pip3 install conan --user --upgrade
  - pip3 install pathlib --user --upgrade
  - conan user
  - conan remote add jeffw https://api.bintray.com/conan/jeffw387/conan-public
script:
  - conan profile new --detect default
  - conan profile update settings.cppstd=17 default
  - ./run-build.sh