language: cpp
before_script:
  - sudo add-apt-repository -y ppa:pete-woods/kitware-ninja
  - sudo apt-get update
  - sudo apt install ninja-build
script:
  - mkdir build && cd build && cmake -GNinja .. && ninja
dist: xenial