language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - sudo add-apt-repository -y ppa:ubuntu-desktop/gnome-3-26
  - sudo add-apt-repository -y ppa:graphics-drivers/ppa
  - sudo apt-get update
  - sudo apt install ninja-build libvulkan-dev libvulkan1 vulkan-utils xorg-dev libglu1-mesa-dev python3 python3-pip
  - pip3 install setuptools --user
  - pip3 install conan --user
  - conan user
  - conan remote add jeffw https://api.bintray.com/conan/jeffw387/conan-public
script:
  - mkdir build && cd build && conan install .. --build=missing && conan build ..
dist: xenial