language: 
  - cpp
  - python
dist: xenial
python: 3.7
sudo: true
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ubuntu-desktop/gnome-3-26
            - ppa:graphics-drivers/ppa
          packages:
            - g++-7
            - ninja-build 
            - libvulkan-dev 
            - libvulkan1 
            - vulkan-utils 
            - xorg-dev 
            - libglu1-mesa-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - pip install -r requirements.txt
  - pip install setuptools --user
  - pip install conan --user
  - conan user
  - conan remote add jeffw https://api.bintray.com/conan/jeffw387/conan-public
script:
  - ./run-build.sh